---
title: "Untitled"
author: "Che-Yu Wang"
date: "2024-03-05"
output:
  pdf_document: default
  html_document: default
---


##Introduction 
Missing data refers to the absence of information from a dataset, which is a common problem in statistical analysis and research. This absence can be caused by a variety of factors, including data entry errors and non-responses in surveys. Missing data can have a significant impact on analytical quality, potentially leading to biased or incorrect conclusions if not addressed properly.

# Explaination 
Professor Rohan's course book states that observations missing completely at random (MCAR) are excluded from the dataset, regardless of other variables present. As we discussed in Chapter 6, MCAR data make summary statistics and inference easier. However, data is rarely MCAR. Even if they were open to it, it would be difficult to convince them. We can still simulate an example, however. For example, we can remove population data from three randomly selected states (Alexander, 2023). However, in statistics, "missing data" refers to the absence of data values for a variable in an observation. This can have a significant impact on the conclusions drawn from the data. This could be due to people not responding, dropping out, or attrition. People can choose not to respond to items or units, and they can withdraw from longitudinal studies. Missing data is common in economics, sociology, and political science because governments or private organizations fail to report important statistics or the information is unavailable. Missing values can also result from researcher errors or poor data collection. They are missing completely, missing at random, and missing not at random. Each type has a unique impact on the validity of the conclusions. Missing data can be handled in the same way as censored data.
However, Missing data is an important issue in data analysis because it means that values that were not observed give us incomplete information. There may not have been a response to the survey or there were mistakes in the data collection and transmission. However, Data that is missing can be put into three groups: missing completely at random (MCAR), missing at random (MAR), and missing not at random (MNAR). Missing data makes statistical conclusions less valid and reliable. This leads to biased estimates, less statistical power, and more work when analyzing the data. Several plans have been made to deal with this problem, each one specific to a different situation and type of missing information. If you delete cases with missing values listwise, they will not be included in the analysis. However, if the missing values are not MCAR, you may lose useful information and be biased. To fix any possible biases, imputation techniques, model-based methods, and weighting methods all take into account the fact that data might be missing.

Moreover, to learn more about how complicated missing data is, as Professor Rohan explained, it is important to know how the different types of missing data are classified (MCAR, MAR, and MNAR) as well as what this means for the validity and reliability of research. However, the several imputation, model-based approaches like Maximum Likelihood Estimation (MLE) and Bayesian inference, sensitivity analysis, and new machine learning techniques are all advanced ways to deal with missing data. These methods offer strong ways to reduce the biases and uncertainties that missing data can cause. These complex methods make sure that statistical analysis is correct and honest, showing how important it is to follow strict rules when working with data. By looking at these advanced methods and how they are used in different research settings, we can understand how important it is to be proactive and well-informed about dealing with missing data, which will ultimately make research findings more reliable and applicable to other situations. This in-depth analysis not only meets the professor's request for a more thorough look, but it also shows how important it is to fill in missing data when trying to come to solid statistical conclusions.

In conclusion, Professor Rohan's course book explains that missing data (MCAR) refers to the absence of data values for a variable in an observation, which can significantly impact conclusions. This can be due to people not responding, dropping out, or attrition. Missing data is common in economics, sociology, and political science due to government or private organizations failing to report important statistics or information being unavailable. Missing data can be categorized into missing completely at random (MCAR), missing at random (MAR), and missing not at random (MNAR). Missing data makes statistical conclusions less valid and reliable, leading to biased estimates and less statistical power. Various plans have been developed to address this problem, including imputation techniques, model-based methods, and weighting methods.

